Episode info template draft
netters42/episodes pull request #2
Opened 2023-02-13 19:12 UTC by amuradyan

Ideas?

2023-02-13 19:17 UTC, amuradyan commented
Ինձ անունը դուր չի գալիս ֆայլի, բայց մտքովս ավելի լավ բան չանցավ։ Սրա ու `template`-ի մեջ էի ընտրում։

2023-02-13 19:35 UTC, antranigv requested changes
մի քանի բան արժի փոխել formatting֊ի մէջ, ու ապա կարող ենք սա merge անել։

երեւի նաեւ արժի notes֊ի notes֊ը լինի հայերէն։ այսինքն `the list of notes ... timecode` լինի հայերէն (։

2023-02-13 19:35 UTC, antranigv commented on DD-MM-YYYY.txt
> +TYPE: <content type> # e.g ցանցառներ ռադիօ>
կարծում եմ որ վերջին `>`֊ն աւելորդ է։ գուցէ մարդիկ շփոթեն

2023-02-13 19:35 UTC, antranigv commented on DD-MM-YYYY.txt
> +NOTES: <
նոյնպէս էլ էստեղ `<`֊ն է աւելորդ։ երեւի տանենք յաջորդ տո՞ղ ուղղակի։

2023-02-13 19:38 UTC, amuradyan commented on DD-MM-YYYY.txt
> +NOTES: <
Ես բացող փակագիծը վերևի տողում եմ թողնում բայց խնդիր չեմ տեսնում տանելու հետ։

2023-02-13 19:46 UTC, amuradyan commented
Թայմկոդ ո՞նց ա հայերեն։

<նշումները՝ տողի վրա մեկական։ Եթե կան թայմկոդեր, ապա տողի սկզբում և հետևյալ տեսքի `hh:mm:ss`։>

2023-02-13 19:46 UTC, amuradyan commented on DD-MM-YYYY.txt
> +TYPE: <content type> # e.g ցանցառներ ռադիօ>
վստահ։ թայփո էր։

2023-02-19 07:39 UTC, antranigv commented
> Թայմկոդ ո՞նց ա հայերեն

ինձ թւում ա «ժամանակակտօր» շատ սիրուն ա հնչում։

2023-02-19 16:55 UTC, amuradyan commented
done

2023-02-19 20:17 UTC, merged